export interface RepoIndexPackage {
  name: string;
  slug: string;
  statementCount: number;
  workflowRunUrl?: string | null;
  rekorLogIndex?: number | null;
  hasBundle?: boolean;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Builds a static index.html landing page for the gh-pages branch, since GitHub Pages doesn't do directory listings. */
export function buildRepoIndexHtml(params: {
  repoName: string;
  description: string;
  packages: RepoIndexPackage[];
  updateInterval: string;
  updatedAt: string;
}): string {
  const { repoName, description, packages, updateInterval, updatedAt } = params;

  const rows = packages
    .map((p) => {
      const slug = encodeURIComponent(p.slug);
      const signedLinks: string[] = [];
      if (p.hasBundle) {
        signedLinks.push(`<a href="pkg/oci/${slug}/vex.json.bundle">bundle</a>`);
      }
      if (p.rekorLogIndex != null) {
        signedLinks.push(
          `<a href="https://search.sigstore.dev/?logIndex=${p.rekorLogIndex}" target="_blank" rel="noreferrer">Rekor entry</a>`
        );
      }
      if (p.workflowRunUrl) {
        signedLinks.push(`<a href="${escapeHtml(p.workflowRunUrl)}" target="_blank" rel="noreferrer">signing run</a>`);
      }
      const signedCell = signedLinks.length > 0 ? signedLinks.join(" · ") : "—";

      return `        <tr>
          <td>${escapeHtml(p.name)}</td>
          <td><code>${escapeHtml(p.slug)}</code></td>
          <td>${p.statementCount}</td>
          <td><a href="pkg/oci/${slug}/vex.json">vex.json</a></td>
          <td>${signedCell}</td>
        </tr>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(repoName)}</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 760px;
    margin: 3rem auto;
    padding: 0 1.5rem;
    line-height: 1.55;
    color: #1a1a1a;
    background: #fff;
  }
  @media (prefers-color-scheme: dark) {
    body { color: #e5e5e5; background: #121212; }
    code, pre { background: #1e1e1e !important; }
    th, td { border-color: #333 !important; }
    a { color: #7db8ff; }
  }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .subtitle { color: #666; margin-top: 0; }
  code, pre { background: #f4f4f4; border-radius: 4px; padding: 0.15rem 0.4rem; font-size: 0.9em; }
  pre { padding: 0.75rem 1rem; overflow-x: auto; }
  table { border-collapse: collapse; width: 100%; margin: 1.5rem 0; }
  th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #ddd; font-size: 0.9rem; }
  th { font-weight: 600; }
  footer { margin-top: 3rem; font-size: 0.8rem; color: #888; }
</style>
</head>
<body>
  <h1>${escapeHtml(repoName)}</h1>
  <p class="subtitle">${escapeHtml(description)}</p>

  <p>This is a Trivy-compatible <a href=".well-known/vex-repository.json">VEX repository</a> —
  a static set of <a href="https://openvex.dev/" target="_blank" rel="noreferrer">OpenVEX</a>
  statements vulnerability scanners can use to suppress findings already assessed as not exploitable.</p>

  <h2>Consuming this repository</h2>
  <pre><code>trivy image --vex repo &lt;image&gt;</code></pre>
  <p>Trivy discovers this repository via the manifest at
  <code>.well-known/vex-repository.json</code>, downloads the archive it points to, and
  matches findings against the packages listed below.</p>

  <h2>Verifying a signature</h2>
  <p>Each document is signed keylessly via GitHub Actions OIDC (Fulcio/Rekor).
  The <strong>Signed</strong> column below links to the signing bundle, its
  public transparency log entry, and the workflow run that produced it — you
  don't need to trust this page, you can check independently:</p>
  <pre><code>cosign verify-blob --bundle vex.json.bundle \
  --certificate-oidc-issuer https://token.actions.githubusercontent.com \
  --certificate-identity-regexp ".*" \
  pkg/oci/&lt;slug&gt;/vex.json</code></pre>

  <h2>Published packages</h2>
  <table>
    <thead><tr><th>Product</th><th>Slug</th><th>Statements</th><th>Document</th><th>Signed</th></tr></thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <footer>
    Updated ${escapeHtml(updatedAt)} · refresh interval ${escapeHtml(updateInterval)} · generated by vex-ui
  </footer>
</body>
</html>
`;
}
